title: "Book Series"
description: "A Jekyll theme for chapter-based book websites"
url: "https://ra559.github.io"
baseurl: "/newgameplus"
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"
permalink: /:categories/:title/
future: true
